[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_API_URL = "https://api.novaframerealty.com"

[context.deploy-preview.environment]
  VITE_API_URL = "https://staging-api.novaframerealty.com"

# Enable PR deploy previews and Netlify Analytics in the Netlify UI.
# Set custom domain to novaframerealty.com via the domain settings page.
